version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dhairyaveera
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cu_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://dhairyaveera:password@postgres:5432/cu_marketplace
    ports:
      - "5003:5003"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "5002:5002"
    depends_on:
      - backend
      - redis

volumes:
  postgres_data: